"""add_missing_indices

Revision ID: a45bad80df32
Revises: d5e78f9a1b2c
Create Date: 2026-05-22 12:59:34.100503

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a45bad80df32"
down_revision: Union[str, None] = "d5e78f9a1b2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_api_keys_is_active"), "api_keys", ["is_active"], unique=False)
    op.create_index(
        op.f("ix_hedge_fund_flow_run_cycles_cycle_number"), "hedge_fund_flow_run_cycles", ["cycle_number"], unique=False
    )
    op.create_index(
        op.f("ix_hedge_fund_flow_run_cycles_status"), "hedge_fund_flow_run_cycles", ["status"], unique=False
    )
    op.create_index(op.f("ix_hedge_fund_flow_runs_status"), "hedge_fund_flow_runs", ["status"], unique=False)
    op.create_index(
        op.f("ix_hedge_fund_flow_runs_trading_mode"), "hedge_fund_flow_runs", ["trading_mode"], unique=False
    )
    op.create_index(op.f("ix_hedge_fund_flows_is_template"), "hedge_fund_flows", ["is_template"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hedge_fund_flows_is_template"), table_name="hedge_fund_flows")
    op.drop_index(op.f("ix_hedge_fund_flow_runs_trading_mode"), table_name="hedge_fund_flow_runs")
    op.drop_index(op.f("ix_hedge_fund_flow_runs_status"), table_name="hedge_fund_flow_runs")
    op.drop_index(op.f("ix_hedge_fund_flow_run_cycles_status"), table_name="hedge_fund_flow_run_cycles")
    op.drop_index(op.f("ix_hedge_fund_flow_run_cycles_cycle_number"), table_name="hedge_fund_flow_run_cycles")
    op.drop_index(op.f("ix_api_keys_is_active"), table_name="api_keys")
    # ### end Alembic commands ###
